name: Summarize Issue and Linked PRs on Project Review

on:
  project_v2_item:
    types: [edited]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
      projects: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Extract Issue Number & Check Status
        id: get-issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BERNARD_BROWSER_AGENT_SUMMARY }}
          script: |
            // Get the project item data
            const item = context.payload.project_v2_item;
            // You may need to query the API for the latest field values
            // For example, using graphql to get field values and status
            const { data } = await github.graphql(`
              query($id: ID!) {
                node(id: $id) {
                  ... on ProjectV2Item {
                    content {
                      ... on Issue { number }
                    }
                    fieldValues(first: 10) {
                      nodes {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          name
                          field {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, { id: item.node_id });
            // Find the status field (adjust if you use a different field name)
            const statusField = data.node.fieldValues.nodes.find(
              n => n.field?.name?.toLowerCase() === 'status'
            );
            const status = statusField ? statusField.name : null;
            const issueNumber = data.node.content?.number;
            // Set outputs
            core.setOutput('status', status);
            core.setOutput('issue', issueNumber);

      - name: Summarize with Copilot
        if: steps.get-issue.outputs.status == 'Review' && steps.get-issue.outputs.issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ steps.get-issue.outputs.issue }}"
          REPO="${{ github.repository }}"

          PRS=$(gh pr list --search "#$ISSUE_NUMBER" --json number --jq '.[].number')

          PR_URLS=""
          for PR in $PRS; do
            PR_URLS="$PR_URLS https://github.com/$REPO/pull/$PR"
          done

          PROMPT="Summarize issue #$ISSUE_NUMBER and the following linked pull requests: $PR_URLS. For each PR, summarize the main code changes and provide a test plan describing how to verify the implementation is correct."

          gh copilot agent-task \
            --issue "$ISSUE_NUMBER" \
            --prompt "$PROMPT" \
            --post-comment
