name: Summarize Issue and Linked PRs in Project Review

on:
  schedule:
    - cron: '* * * * *' # every minute; GitHub may delay runs

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find issues in Review status
        env:
          GH_TOKEN: ${{ secrets.BERNARD_BROWSER_AGENT_SUMMARY }}
        run: |
          PROJECT_ID="PVT_kwHOBtn0hM4BEg5v"
          REVIEW_OPTION_ID="df73e18b"

          echo "---- Running GraphQL query to fetch Project items ----"
          gh api graphql -f query='
            query {
              node(id: "'$PROJECT_ID'") {
                ... on ProjectV2 {
                  items(first: 100) {
                    nodes {
                      content {
                        ... on Issue { number }
                      }
                      fieldValues(first: 20) {
                        nodes {
                          ... on ProjectV2ItemFieldSingleSelectValue { optionId }
                        }
                      }
                    }
                  }
                }
              }
            }
          ' > items.json

          echo "---- Extracting issue numbers in Review status ----"
          ISSUE_NUMBERS=$(jq -r --arg REVIEW_OPTION_ID "$REVIEW_OPTION_ID" '
            .data.node.items.nodes[]
            | select(.fieldValues.nodes[]?
                | select(.optionId == $REVIEW_OPTION_ID))
            | .content.number
          ' items.json | xargs)

          echo "Extracted ISSUE_NUMBERS: '$ISSUE_NUMBERS'"
          echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV

      - name: Summarize with OpenAI and comment
        if: env.ISSUE_NUMBERS != ''
        env:
          GH_TOKEN: ${{ secrets.BERNARD_BROWSER_AGENT_SUMMARY }}
          OPENAI_API_KEY: ${{ secrets.OPEN_API_KEY }}
        run: |
          REPO="bernardhealth/bernard-browser-use"
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            LABELS=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json labels --jq '.labels[].name')
            if echo "$LABELS" | grep -q '^copilot-reviewed$'; then
              echo "Issue #$ISSUE_NUMBER already summarized, skipping."
              continue
            fi

            ISSUE_TITLE=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json title --jq '.title')
            ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json body --jq '.body')
            PRS=$(gh pr list --repo "$REPO" --search "#$ISSUE_NUMBER" --json number --jq '.[].number')
            PR_SUMMARIES=""

            for PR in $PRS; do
              PR_TITLE=$(gh pr view "$PR" --repo "$REPO" --json title --jq '.title')
              PR_BODY=$(gh pr view "$PR" --repo "$REPO" --json body --jq '.body')
              PR_SUMMARIES="$PR_SUMMARIES\nPR #$PR: $PR_TITLE\n$PR_BODY\n"
            done

            PROMPT="Summarize the following GitHub issue and its linked PRs. For each PR, summarize the main code changes and provide a test plan describing how to verify the implementation is correct.

Issue #$ISSUE_NUMBER: $ISSUE_TITLE
$ISSUE_BODY

$PR_SUMMARIES"

            SUMMARY=$(curl -s https://api.openai.com/v1/chat/completions \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -d '{
                "model": "gpt-3.5-turbo",
                "messages": [
                  {"role": "system", "content": "You are an expert open source project reviewer."},
                  {"role": "user", "content": "'"${PROMPT//$'\n'/\\n}"'"}
                ],
                "max_tokens": 500
              }' | jq -r '.choices[0].message.content')

            gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "### OpenAI Summary\n$SUMMARY"
            gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "copilot-reviewed"
          done
