name: Run Bernard Tests for Issues

on:
  workflow_dispatch:

jobs:
  run-bernard-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .
          pip install gh

      - name: Find issues with needs-test label
        id: find_issues
        run: |
          gh issue list --label needs-test --state open --json number,title,body > issues.json

      # Next steps will process each issue and run your program
      # We'll add those in the next iteration
